[module]
steps = [
    { kind = "install-packages", packages = [
        "alsa-scarlett-gui", # gui for audio interface
        "vulkan-radeon",
        "xf86-video-amdgpu",
        "libva-mesa-driver",
        "mesa-vdpau",

        "lib32-mesa",
        "lib32-vulkan-radeon",
        "lib32-libva-mesa-driver",
        "lib32-mesa-vdpau",
    ] },
]
