[module]
steps = [
   { kind = "install-packages", packages = [
      "btop",
      "obs-studio",
      "imagemagick",
      "qbittorrent",
   ] },
   { kind = "install-packages", packages = [
      "mercury-browser-avx2-bin",
      "vesktop-bin",
   ], aur = true },
   { kind = "copy-file", from = "mercury/syspref.js", to = "/etc/mercury/defaults/pref/syspref.js", as-root = true },
]
