[module]
includes = ["dev/rust.toml", "dev/podman.toml"]

steps = [
    { kind = "install-packages", packages = [
        "zed-preview-bin",
    ], aur = true },
    { kind = "install-packages", packages = ["nodejs", "pnpm", "man-db", "cmake", "ninja"] },
    { kind = "symlink", from = "dev/gitconfig", to = "~/.gitconfig" },
]
