[module]
includes = "greetd.toml"

steps = [
   { kind = "install-packages", packages = [
      "rofi-wayland",                # avoid conflict with rofi later
      "hyprland",
      "xdg-desktop-portal-hyprland",
      "kitty",                       # term
      "nwg-look",                    # gtk settings
      "dunst",                       # notifs
      "libnotify",
      "hypridle",
      "pinta",                       # simple photo editor
      "swww",                        # wallpaper
      "waybar",
      "otf-font-awesome",
      "ttf-fira-sans",               # waybar font
      "ttf-fira-code",
      "ttf-firacode-nerd",
      "tofi",

      "noto-fonts",
      "noto-fonts-cjk",
      "noto-fonts-emoji",
      "noto-fonts-extra",

      # misc
      "blueman",
      "bluez",
      "bluez-utils",
      "nm-connection-editor",
      "wl-clipboard",
      "pavucontrol",
      "polkit-gnome",
      "xdg-user-dirs",
      "gvfs",
      "tumbler",
      "gtk4",
      "libadwaita",
      "qt6ct",
      "flatpak",
      "smile",
      "xdg-desktop-portal-gtk",
      "less",
   ] },

   { kind = "install-packages", packages = [
      "grimblast-git",           # screenshots
      "ttf-jetbrains-mono-nerd",
   ], aur = true },

   { kind = "symlink", from = "dots/hypr", to = "~/.config/hypr", delete-existing = true },
   { kind = "symlink", from = "dots/dunst", to = "~/.config/dunst", delete-existing = true },
   { kind = "symlink", from = "dots/waybar", to = "~/.config/waybar", delete-existing = true },
   { kind = "symlink", from = "dots/rofi", to = "~/.config/rofi", delete-existing = true },
   { kind = "symlink", from = "dots/tofi", to = "~/.config/tofi", delete-existing = true },
]
