[module]
includes = [
   "../modules/lily/keys.toml", # runs first due to requiring user presence
   "nya/hardware.toml",

   "../modules/hyprland.toml",
   "../modules/pipewire.toml",

   "../modules/dots.toml",
   "../modules/apps.toml",
   "../modules/dev.toml",
   "../modules/virt.toml",

   "../modules/lily/gaming.toml",
]
