[module]
steps = [
    { kind = "install-packages", packages = [
        "crun",           # provides oci-runtime, either crun or runc
        "podman",
        "podman-docker",
        "podman-compose",
        "aardvark-dns",
    ] },
    { kind = "copy-file", from = "podman/10-unqualified-search-registries.conf", to = "/etc/containers/registries.conf.d/10-unqualified-search-registries.conf", as-root = true },
]
